//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlitBit.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlitBit.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit must be between 0 and 31 inclusive.
        /// </summary>
        internal static string Chk_ExpectedOffsetIn32BitRange {
            get {
                return ResourceManager.GetString("Chk_ExpectedOffsetIn32BitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset would result in buffer overrun.
        /// </summary>
        internal static string Chk_OffsetWouldResultInBufferOverrun {
            get {
                return ResourceManager.GetString("Chk_OffsetWouldResultInBufferOverrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reactor has stopped and cannot perform the operation.
        /// </summary>
        internal static string Err_ReactorStopped {
            get {
                return ResourceManager.GetString("Err_ReactorStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status&lt;E&gt; requires typeof(E) be an enum.
        /// </summary>
        internal static string Err_StatusTypeMustBeEnum {
            get {
                return ResourceManager.GetString("Err_StatusTypeMustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsyncResult values are write-once and the value has already been set.
        /// </summary>
        internal static string Error_AsyncResultAlreadySet {
            get {
                return ResourceManager.GetString("Error_AsyncResultAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future already has a value; futures are write-once..
        /// </summary>
        internal static string Error_FutureValueAlreadyPresent {
            get {
                return ResourceManager.GetString("Error_FutureValueAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future value not yet available.
        /// </summary>
        internal static string Error_FutureValueNotAvailable {
            get {
                return ResourceManager.GetString("Error_FutureValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskState is invalid: expected = {0}; actual = {1}.
        /// </summary>
        internal static string Error_TaskStateInvalidExpect {
            get {
                return ResourceManager.GetString("Error_TaskStateInvalidExpect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParallelTask threw an unhandled exception, see the inner exception for details.
        /// </summary>
        internal static string Error_TaskUnhandledException {
            get {
                return ResourceManager.GetString("Error_TaskUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlitBit Resource Client v.
        /// </summary>
        internal static string ResourceClientName {
            get {
                return ResourceManager.GetString("ResourceClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskBoundary #{0}.
        /// </summary>
        internal static string TaskBoundaryName {
            get {
                return ResourceManager.GetString("TaskBoundaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncaught exception while disposing cleanup scope.
        /// </summary>
        internal static string Warn_ErrorWhileDisposingCleanupScope {
            get {
                return ResourceManager.GetString("Warn_ErrorWhileDisposingCleanupScope", resourceCulture);
            }
        }
    }
}
